environment:
  ELM_VERSION: "0.17.1"
  matrix:
  - nodejs_version: "5.0"

platform:
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - npm install -g elm@%ELM_VERSION%
  - npm install

build:
  - npm run build-ci

test_script:
  - npm run test-console

build: off
